### ISSUE TITLE
Older GS Mode Selector Sample Icon

### ISSUE THREAD

**Issue by lain32** [israpps/wLaunchELF_ISR_HDD#1]
Not much of a problem but I just like to note that your HEADER SAMPLES for PP.GMS is using my older icon that was for 0.37
I made a nicer one using the artwork from [PS2 Home - GSM](https://www.ps2-home.com/forum/viewtopic.php?t=53)

Hare is my new icon if you like to use it. [GSM Icon](https://github.com/israpps/wLaunchELF_ISR_HDD/files/6603019/GMS.zip) You can also find the HDD Img it was used in at [Archive.org - HDDOSD 100J 48BIT](https://archive.org/details/PS2_HDDOSD_100J_48BIT)

**Comment by israpps** [comment]
> Not much of a problem but I just like to note that your HEADER SAMPLES for PP.GMS is using my older icon that was for 0.37
> I made a nicer one using the artwork from [PS2 Home - GSM](https://www.ps2-home.com/forum/viewtopic.php?t=53)
> 
> Hare is my new icon if you like to use it. [GSM Icon](https://github.com/israpps/wLaunchELF_ISR_HDD/files/6603019/GMS.zip) You can also find the HDD Img it was used in at [Archive.org - HDDOSD 100J 48BIT](https://archive.org/details/PS2_HDDOSD_100J_48BIT)
Hi!
I'll take a look at that icon in a few hours...
Regarding the HDD-OSD....
I prefer HDD-OSD 1.10U manually extracted from SUDC4

**Comment by lain32** [comment]
> Regarding the HDD-OSD....
> I prefer HDD-OSD 1.10U manually extracted from SUDC4

Yeah the HDDOSD 1.00J 48BIT (LBA48) files are by SP193 and "someone who wishes to remain anonymous"
In the downloads is a 7zip that has just the SYSCONF & SYSTEM files. It may be useful for users who have SCPH-1x000.
(It does however work on all FAT models, I used it upto a DTL-H50001 model)

**Comment by israpps** [comment]
> > Regarding the HDD-OSD....
> > I prefer HDD-OSD 1.10U manually extracted from SUDC4
> 
> Yeah the HDDOSD 1.00J 48BIT (LBA48) files are by SP193 and "someone who wishes to remain anonymous"
> In the downloads is a 7zip that has just the SYSCONF & SYSTEM files. It may be useful for users who have SCPH-1x000.
> (It does however work on all FAT models, I used it upto a DTL-H50001 model)

1.10U has native 48bit support
